export const ErrorCodes = {
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PRECONDITION_REQUIRED: 'PRECONDITION_REQUIRED',
  ETAG_MISMATCH: 'ETAG_MISMATCH',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];