name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          cd cdk && npm ci
          cd ./../app/backend && npm ci

      - name: Lint Backend
        run: npm run lint
        working-directory: app/backend

      - name: Typecheck Backend
        run: npm run typecheck
        working-directory: app/backend

      - name: Test Backend
        run: npm run test
        working-directory: app/backend

      - name: CDK Synth
        run: npx cdk synth
        working-directory: cdk