name: Deploy Dev

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::961341533599:role/GitHubActionsCdkRole
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          npm ci
          cd cdk && npm ci
          cd ./../app/backend && npm ci

      - name: CDK Diff
        working-directory: cdk
        run: npx cdk diff -c env=dev

      - name: CDK Deploy (Dev)
        working-directory: cdk
        run: npx cdk deploy -c env=dev --require-approval never